### ISSUE TITLE
Some simple example code?

### ISSUE THREAD

**Issue by mperino** [1937Elysium/Ovl-Python#1]
Hello,

Wondering if you have some simple example code or other documentation?

Thanks!

**Comment by 1937Elysium** [comment]
Hey there, there is documentation on many functions and classes in the English directory, please look over there.
Additionally, there is some sample code (here)[https://github.com/1937Elysium/Ovl-Python/blob/master/English/ovl/Vision/Constructer%20(__init__).md].

**Comment by mperino** [comment]
Toda rabah.
